language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
# dependencies
install:
  - pip install numpy>=1.15.0 scipy cupy>=7.3 gputil
before_script:
  - cd test
# command to run tests
script:
  - python -m unittest test_vectors.TestVector
  - python -m unittest test_vectors.TestSuperVector
  - python -m unittest test_vectors.TestVectorIC
